.TH "usenew" "1" 
.SH "SYNOPSIS"
.PP
\fBusenew\fP \fI[options]\fP \fI[prefix]\fP <command/file> \fI[start taget options]\fP 

.SH "OPTIONS"
.SS "general options:"
.TP
\fB-g    --gui        \fP
enable gui output
.TP
\fB-h    --help       \fP
show help
.TP
\fB-H    --long-help  \fP
show this text, long help
.TP
\fB-V    --version    \fP
show version
.TP
\fB--revision         \fP
show revision
.TP
\fB-v --verbose       \fP
be more verbose
.TP
\fB--debug            \fP
help us in debuging
.SS "options:"
.TP
\fB-b    --binpath <binpath> \fP
define in wich path usenew will search for wine and CO
.TP
\fB-r    -run-debug          \fP
don't set WINEDEBUG to default (see \fIENVIRONMENT\fP)
.TP
\fB-d    --desktop           \fP
start file/command in virtual desktop
.TP
\fB-D    --directory         \fP
tell usenew to change directory to started file
.TP
\fB-p    --prefix            \fP
replacement for prefix, usenew will ask for prefix is this option is given ( usefull to start Windows programms out of file manager)
.SS "commands:"
.TP
\fBwinefile\fP
open winefilebrowser
.TP
\fBwinecfg \fP
open winecontrol
.TP
\fBappconf \fP
control the software of the chosen prefix
.TP
\fBcontrol \fP
open control
.TP
\fBcmd     \fP
open winecommandline
.TP
\fBopen    \fP
open prefix directory with xdg-open
.SS "file specific  options:"
.SS "\fB.bat/\fP.cmd file"
.TP
\fB-w, --window\fP
open file in new window

.SS "*.reg file"
.TP
\fB-i\fP
import regefile
.TP
\fB-e\fP
export the given part of registry to file
syntax for export to regfile :
usenew [prefix] [regfilename.reg] -e [regpath]
.SH "ENVIRONMENT"
.TP
\fBWINEPATH\fP
set path where usenew searchs for wine
.TP
\fBWINEPREFIX_\d\s-2PATH\s+2\u\fP
path where usenew searches for wineprefixs, default is $HOME
.TP
\fBWINEDEBUG\fP
we do nothing with it, will not overridden by \fBusenew\fP if set

.SH "SEE ALSO"
.PP
\fIwine\fP(1), \fIlibuse\fP(1)
