SHPP=shpp
DESTDIR       =
PREFIX        = /usr/local 
INSTALL       = /usr/bin/env install 
MSGFMT        = /usr/bin/msgfmt
SED           = /bin/sed
bindir        = $(PREFIX)/bin
libdir        = $(PREFIX)/lib
sysconfdir    = $(PREFIX)/etc
